### ISSUE TITLE
Chess string result doesn't match type for ArchivesGame

### ISSUE THREAD

**Issue by jo-sip** [davipccunha/chess-com#1]
The types for GameResult shows as "checkmated" | "agreed" | "repetition" | "timeout" | "resigned" | "stalemate" | "lose" | "insufficient" | "50move" | "abandoned" | "timevsinsufficient", but I get a text string like "Lost by Checkmate".

Thanks.

**Comment by davipccunha** [comment]
I'll take a look at that and keep you updated. Thanks for filing the issue.

**Comment by davipccunha** [comment]
ArchivesGame#result now consistently has same possibilities as shown in ResultOptions enum as of package version 1.3.0.
```typescript
'Win' | 'Checkmated' | 'Agreed' | 'Repetition' | 'Timeout' | 'Resigned' | 'Stalemate' | 'Lose' | 'Insufficient' | '50move' | 'Abandoned' | 'Timevsinsufficient'
```
